{% set version = '0.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xplorerr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/xplorerr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/xplorerr/xplorerr_{{ version }}.tar.gz
  sha256: 49e8f7aecddb5ad3d6684aebe433e7ee7732096d47171400e62fe6579e05ce61

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-shiny
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp
    - r-shiny

test:
  commands:
    - $R -e "library('xplorerr')"           # [not win]
    - "\"%R%\" -e \"library('xplorerr')\""  # [win]

about:
  home: https://xplorerr.rsquaredacademy.com/
  dev_url: https://github.com/rsquaredacademy/xplorerr
  license: MIT
  summary: Tools for interactive data exploration built using 'shiny'. Includes apps for descriptive
    statistics, visualizing probability distributions, inferential statistics, linear
    regression, logistic regression and RFM analysis.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: xplorerr
# Type: Package
# Title: Tools for Interactive Data Exploration
# Version: 0.2.0
# Authors@R: person("Aravind", "Hebbali", email = "hebbali.aravind@gmail.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0001-9220-9669"))
# Description: Tools for interactive data exploration built using 'shiny'. Includes apps for descriptive statistics, visualizing probability distributions, inferential statistics, linear regression, logistic regression and RFM analysis.
# Depends: R(>= 3.2.4)
# Imports: Rcpp, shiny, utils
# Suggests: blorr, data.table, descriptr, DT, haven, highcharter, jsonlite, magrittr, olsrr, plotly, readr, readxl, rfm, shinyBS, shinycssloaders, standby, tools, vistributions
# URL: https://github.com/rsquaredacademy/xplorerr, https://xplorerr.rsquaredacademy.com/
# BugReports: https://github.com/rsquaredacademy/xplorerr/issues
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.3.2
# LinkingTo: Rcpp
# NeedsCompilation: yes
# Packaged: 2024-10-29 10:49:53 UTC; HP
# Author: Aravind Hebbali [aut, cre] (<https://orcid.org/0000-0001-9220-9669>)
# Maintainer: Aravind Hebbali <hebbali.aravind@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-10-29 11:30:02 UTC
